name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
  github-metrics-wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: languages, languages-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
  github-metrics-xkcd:
    runs-on: ubuntu-latest
    steps:
      - name: XKCD of the day
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.screenshot.svg
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"
  github-metrics-stock:
    runs-on: ubuntu-latest  
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stock.ytd.svg
          token: NOT_NEEDED
          base: ""
          plugin_stock: yes
          plugin_stock_token: ${{ secrets.STOCK_TOKEN }}
          plugin_stock_symbol: ACWI
          plugin_stock_duration: ytd
          plugin_stock_interval: 60m
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stock.5d.svg
          token: NOT_NEEDED
          base: ""
          plugin_stock: yes
          plugin_stock_token: ${{ secrets.STOCK_TOKEN }}
          plugin_stock_symbol: ACWI
          plugin_stock_duration: 5d
          plugin_stock_interval: 60m




